import Head from "next/head";

import Categories from "@/components/Categories/Categories";
import Hero from "@/components/Hero/Hero";
import Statistics from "@/components/Statistics/Statistics";
import RecommendedSiders from "@/components/RecommendedSiders/RecommendedSiders";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/favicon.ico" />
        <title>Online Platform</title>
      </Head>
      <Hero />
      <Statistics />
      <Categories />
      {/* <RecommendedSiders/>    */}
    </>
  );
}
