import Head from "next/head";

import Main from "./Main/Main";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/icon.svg" />
        <title>Online Platform</title>
      </Head>
      <Main />
    </>
  );
}
