import Hero from '@/components/Hero/Hero'
import Statistics from '@/components/Statistics/Statistics'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Statistics/>
   
    </>
  )
}
